### ISSUE TITLE
`var` declarations can't be rerun

### ISSUE THREAD

**Issue by kevinburke** [gopherds/gophernotes#40]
This code snippet: 

```go
:import "github.com/go-yaml/yaml"
:import "fmt"

var data = `
a: Easy!
b:
  c: "\xf6\xac"
`

type T struct {
        A string
        B struct {
                RenamedC []byte   `yaml:"c"`
        }
}

t := T{}

err := yaml.Unmarshal([]byte(data), &t)
if err != nil {
    fmt.Printf("error: %v", err)
}
fmt.Printf("%#v\n", t)
```

fails when you run it twice, with the following error:

```
gophernotes_session.go:36: data redeclared in this block
	previous declaration at /var/folders/dx/x6gx95t14n7bb3v878968fkm0000gn/T/842705212/gophernotes_session.go:19
```

**Comment by dwhitena** [comment]
Interesting.  Good catch.

**Comment by dwhitena** [comment]
I have been thinking about this.  I think that this may be one behavior that we want to keep.  In general, Jupyter provides interactive programming similar to interactive programming in a REPL, except in Jupyter the code is executed in cells (and of course there are other features, etc.).  However, in a REPL, or even in other Jupyter kernels, your history of execution remains as you execute more code.  Thus, for any language you can redeclare, delete, etc. variable such that if you re-run a cell (that previously executed without error) you can encounter an error.  That is, a Jupyter kernel should not overwrite processes that are illegal in a language, at least for the most part.

For example, if someone is using gophernotes to teach some Go, we wouldn't want them teaching that you can redefine a variable via `var`, as that is illegal.  There is some unavoidable modification of normal Go procedure here in that we don't have an explicit `func main` and we are programming in cells.  However, things like re-declaring via `var` should remain the same I think.

I think the proper way to deal with this issue is to restart the kernel in Jupyter or to modify the cell to only utilize the variable instead of redeclare it.  Thoughts @kevinburke?

**Comment by dwhitena** [comment]
Closing this for now, but please comment here and/or re-open if you feel strongly that this should be discussed further or addressed in some other way.
